### ISSUE TITLE
policy for sharing C headers across modules

### ISSUE THREAD

**Issue by martinschwinzerl** [xsuite/xfields#19]
Not an urgent issue but a general question:

PR #17 introduces helper functions `xsuite_sincos` and `power_n`. For `xsuite_sincos`, there there are potential use-cases in xsuite/xtrack (like for example the map for the SRotation beam element) and I've heard at least one user expressing interest in using `power_n`also in a different context. 

Ideally, we should be able to share these headers across [xsuite/xtrack](https://github.com/xsuite/xtrack), [xsuite/xpart](https://github.com/xsuite/xpart), etc. without having to duplicate them, especially if we end up having them drifting apart. Is there already a policy or plan to do this or is duplication positively intended to provide maximum decoupling between modules?

One idea would be to generate them from python in one module and call them whenever these functions are needed.

**Comment by giadarol** [comment]
I think we can assume the following dependencies:
 - xtrack depends on xobjects
 - xfields depends on xtrack and xobjects

One can include header files from an upstram package by doing something like this:
```python
# For example in xfields we want to include a header from xtrack
sources.append(xtrack._pkg_root.joipath('header/contstants.h')
```
