### ISSUE TITLE
inconsistencies in examples

### ISSUE THREAD

**Issue by martinschwinzerl** [xsuite/xfields#20]
There are inconsistencies in some `examples/exploratory_scripts/` examples, e.g. `007_function_in_kernel/000_play.py` using wrong (outdated?) keywords and structure for the kernel definitions. Since examples are not run as part of the continous integration / pytest cycle, that's kind of expected (at least that's the problem we have in SixTrackLib).

I'm unfortunately not able to spend a lot of time on this but I could for example fix issues I encounter while trying to get the hang of the whole API -> please let me know if that would be useful.

**Comment by martinschwinzerl** [comment]
Cf. PR #22

**Comment by giadarol** [comment]
Outdated
