### ISSUE TITLE
beambeam tests

### ISSUE THREAD

**Issue by pkicsiny** [xsuite/xfields#64]
Running pytest on the beambeam tests on a mac with only a CPU gives 2 failures:

`test_beambeam3d.py` fails with:

`pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE`

`test_spacecharge.py` fails with:

`ModuleNotFoundError: No module named 'gpyfft'`

Both related to OpenCL.

**Comment by giadarol** [comment]
Happened because @pkicsiny had a non working pyopencl installation. All fine after ```pip uninstall pyopencl```
